version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P YourStrong!Passw0rd -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 10
    volumes:
      - ./mssql-init:/docker-entrypoint-initdb.d
  # Removed custom command for migration; handled by separate service
  mssql-migrate:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - mssql
    volumes:
      - ./mssql-init:/mssql-init
    entrypoint: /bin/bash -c "sleep 40 && /opt/mssql-tools/bin/sqlcmd -S mssql -U SA -P YourStrong!Passw0rd -i /mssql-init/init.sql"

  redis:
    image: redis:7.2-alpine
    ports:
      - "6380:6379"

  producer:
    build: ./producer
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: kafka:9092
    restart: on-failure

  consumer:
    build: ./consumer
    depends_on:
      - kafka
      - mssql
      - redis
    environment:
      KAFKA_BROKER: kafka:9092
      KAFKA_TOPIC: events
      KAFKA_GROUP_ID: event-consumer-group
      SQL_SERVER_DSN: "sqlserver://SA:YourStrong!Passw0rd@mssql:1433?database=eventdb"
      REDIS_ADDR: redis:6379
    restart: on-failure

  api:
    build: ./api
    depends_on:
      - mssql
    environment:
      SQLSERVER_CONN: "sqlserver://SA:YourStrong!Passw0rd@mssql:1433?database=eventdb"
    ports:
      - "8080:8080"
    restart: on-failure
